### ISSUE TITLE
Errors for swift 3

### ISSUE THREAD

**Issue by kunalgupta1593** [ilyapuchka/ReadMoreTextView#11]
I am trying to use this library on swift 3 and xcode 8.0 but it shows many error. can you please help

**Comment by ilyapuchka** [comment]
I'm sorry, but without any specific error that you get I can not help. The component supports both Swift 2.3 and Swift 3 and if you check example project there are no issues. Feel free to reopen the issue when you have time to properly describe it. Cheers.
