### ISSUE TITLE
Got infinite table view scroll when press read more/less inside tableview in iPhone 6s

### ISSUE THREAD

**Issue by Maheepk** [ilyapuchka/ReadMoreTextView#12]
@ilyapuchka  am using this library, i messed up with one issue in iPhone 6s when tapping more/less inside tableview.

please have a look on this project, i just updated some values in that. Please run this on iPhone 6s screen.

thanks,
[ReadMoreTextView-updated.zip](https://github.com/ilyapuchka/ReadMoreTextView/files/710708/ReadMoreTextView-updated.zip)

**Comment by ilyapuchka** [comment]
To properly use it in UITableView or in UICollectionView you'll need to do some extra work, for example properly handle cell reuse, preserve scrolling position when expanding/collapsing, properly setup layout for self-sizing, etc.
That's out of scope of the this project itself and out of scope of example project. Even so I have pushed updated example project that should give you some tips for how to solve your issues.
