### ISSUE TITLE
explicit self

### ISSUE THREAD

**Issue by felipeska** [ilyapuchka/ReadMoreTextView#13]
When use the pod and compile, this error appear.

My proyect uses swift 2.3

Any idea?

![captura de pantalla 2017-02-07 a las 11 10 54 a m 2](https://cloud.githubusercontent.com/assets/613443/22699658/1877cb44-ed26-11e6-81fb-5ca4b4cf7fbf.png)

**Comment by ilyapuchka** [comment]
you should use the latest version, this was fixed in 1.1.0
