### ISSUE TITLE
Interface Builder stuck in infinite loop when setting class to ReadMoreTextView

### ISSUE THREAD

**Issue by vl4dimir** [ilyapuchka/ReadMoreTextView#14]
(XCode 8.2.1, ReadMoreTextView 1.2.0 via CocoaPods.)

I can't get Interface Builder to accept ReadMoreTextView as the class for a text view in a storyboard.

Steps to reproduce:
* create new project, add ReadMoreTextView as dependency via CocoaPods
* create new storyboard
* create view controller
* create UITextView
* set text view's class to ReadMoreTextView
* XCode freezes and has to be killed forcefully

I tried copying `ReadMoreTextView.swift` directly into my project and removing the `@IBDesignable` annotation, and then everything works.

**Comment by vl4dimir** [comment]
Note: I just tried opening the [example project](https://github.com/ilyapuchka/ReadMoreTextView/tree/master/Example), XCode freezes as well.

**Comment by ilyapuchka** [comment]
Please check out latest master for fix
