### ISSUE TITLE
Reloading the UITableView and getting the truncated version

### ISSUE THREAD

**Issue by erickva** [ilyapuchka/ReadMoreTextView#15]
Hello,

When I try to reloadData or even reloadRowsAtIndexPaths inside the .onSizeChange block it always show the truncated version with the read more button.

I am doing it in side the cellForRowAtIndexPath.
Is it the wrong place for doing this? I need some guidance. 

Thanks.

**Comment by ilyapuchka** [comment]
@erickva please check example project to see how this can be done. You need to call `setNeedsUpdateTrim` and `layoutIfNeeded` on the text view to update it's content.
