### ISSUE TITLE
Bug: Hard to click see more

### ISSUE THREAD

**Issue by nthtrung09it** [ilyapuchka/ReadMoreTextView#16]
Hi, I use this library in my project.
But I have a problem:
When UITextView is in justify alignment, it's hard to click see more button.
<img width="349" alt="screen shot 2017-05-09 at 12 40 15 am" src="https://cloud.githubusercontent.com/assets/7716509/25817028/402242b6-3450-11e7-9756-0767f6cb7f12.png">
Can you fix this bug? Thanks so much :)

**Comment by ilyapuchka** [comment]
You can use `readMoreTextPadding` property to adjust (i.e. make it larger) tappable area.

**Comment by nthtrung09it** [comment]
Thanks, it works :) And how can I move **(see more)** to right alignment. It should justify whole text.
<img width="374" alt="screen shot 2017-05-13 at 9 09 30 am" src="https://cloud.githubusercontent.com/assets/7716509/26021643/4aac7962-37bc-11e7-91b9-edfb5f4ccfe7.png">

**Comment by ilyapuchka** [comment]
I guess it requires calculating number of characters to trim on the last line a bit differently (or maybe the text container is not setup with proper alignment) because their position is adjusted. Feel free to contribute with PR if you find the way.
