### ISSUE TITLE
ReadMoreTextView with scrolling

### ISSUE THREAD

**Issue by yanivhasbani** [ilyapuchka/ReadMoreTextView#19]
I have a ReadMoreTextView which is inside a stack layout..

I want to have the option, upon expend to scroll, which is the default behavior for UITextView.

Unfortunately, I see that in this implementation you guys disable the scrolling.

Why??

**Comment by ilyapuchka** [comment]
because it's required for proper sizing. scrolling and hugging text are mutually exclusive features. you can enable scrolling manually on expand event though and probably set maximum height constraint for you text view
