### ISSUE TITLE
Setting .shouldTrim to true on iPhone 5S causes text to be cut in half

### ISSUE THREAD

**Issue by GabriellaBLopes** [ilyapuchka/ReadMoreTextView#20]
![image](https://user-images.githubusercontent.com/17458427/29146418-664e6188-7d37-11e7-8bd3-841a71c506c1.png)

This issue only happens on the iPhone 5S. The same code works fine on all other screen sizes. Note that I've set the maximum number of lines to 5 and, in this example, the full text has only 3 lines.

**Comment by ilyapuchka** [comment]
it's probably the same issue as #18, try to check the size of the cell if it matches its final frame on smaller devices

**Comment by GabriellaBLopes** [comment]
I'm not using it on a Table View. The size of the ReadMoreTextView actually doesn't fit the entire content. Also, I'm certain there are no other views "in front" of it.

**Comment by ilyapuchka** [comment]
Can you reproduce this in a clean project?

**Comment by GabriellaBLopes** [comment]
Yes, I can! I realize now that this happens when there are very few characters in the last line.

![image](https://user-images.githubusercontent.com/17458427/29279207-85206caa-80ed-11e7-99f8-cc3ef1829f9a.png)

![image](https://user-images.githubusercontent.com/17458427/29279252-a3e348f6-80ed-11e7-90a1-def64946ea3d.png)

The only difference between these two examples above is the text, I didn't change any code.

**Comment by GabriellaBLopes** [comment]
Hey, @ilyapuchka ! Any updates on this?

**Comment by ilyapuchka** [comment]
Sorry but I couldn't reproduce it with example app. I could help you with debugging this issue if you submit a pr with a sample code that demonstrates the bug. You can also use example application to build the UI.
