### ISSUE TITLE
Button more missing in first time running application

### ISSUE THREAD

**Issue by freishya** [ilyapuchka/ReadMoreTextView#22]
![simulator screen shot aug 24 2017 2 05 40 pm](https://user-images.githubusercontent.com/25956040/29654179-627522f4-88d6-11e7-9c8d-ada54915c103.png)

Thank's your pod is very help me to make first application. But in xcode 8.3.3, ios 10.3, running in simulator Iphone SE found bug. Button more missing in first time application running but if click in area more can see all text. after click less, in second it's display more appear. Hope this bug can clear in next push.

Success!

**Comment by mariokovacevic** [comment]
Hi,

Same issue, is there a workaround?

Thanks

**Comment by freishya** [comment]
@mariokovacevic i use this code and this issue is done. 
let readMoreTextAttributes:_**[String: Any]**_ = [
            NSForegroundColorAttributeName: view.tintColor,
            NSFontAttributeName: UIFont.boldSystemFont(ofSize: 15)
        ]

hope help you.

**Comment by ilyapuchka** [comment]
you probably have a mismatch between font or frame width used when view is created and a final font
