### ISSUE TITLE
Errors for Swift 3

### ISSUE THREAD

**Issue by snehageorge** [ilyapuchka/ReadMoreTextView#30]
I am attaching the image which shows the list of errors I'm getting.
![screen shot 2017-11-08 at 11 26 12 am](https://user-images.githubusercontent.com/25521552/32533675-c95ff23c-c477-11e7-881b-c41d9fee5e3a.png)

**Comment by ilyapuchka** [comment]
Use latest version that supports swift 4

**Comment by snehageorge** [comment]
Which version supports Swift 3 ?
