### ISSUE TITLE
Hide the More text

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [ilyapuchka/ReadMoreTextView#36]
Hi,

I want to hide the "More" text of the text view and rely solely on toggling the `shouldTrim` property to show/hide the extra text like in the example project.

But I noticed setting the `readMoreText` value to either `nil` or an empty text disables the expanding of the textview.

Is there a way to achieve this?

**Comment by ilyapuchka** [comment]
No, because of [this logic](https://github.com/ilyapuchka/ReadMoreTextView/blob/master/Sources/ReadMoreTextView.swift#L250) some adjustments should be made to make this work as you described.

**Comment by Isuru-Nanayakkara** [comment]
That's okay, I kinda worked around it by setting the text color of the read more text to white.
