### ISSUE TITLE
It doesn't work probably when you set the text programmatically 

### ISSUE THREAD

**Issue by mohammad19991** [ilyapuchka/ReadMoreTextView#4]
I tried to add the text like this:
         textView.text = "some long test"
and it's not working, but when I set the text via storyboard it works!

**Comment by saxahan** [comment]
@mohammad19991 yes you're right. It doesn't work with programmatically I've tried, and also it has swift 2.0+ issues.

**Comment by Shawnees** [comment]
This still doesnt work no ?

**Comment by ilyapuchka** [comment]
This works and was working always.
