### ISSUE TITLE
Find if the content exceeds the textview height

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [ilyapuchka/ReadMoreTextView#40]
Hi,

I have a textview that toggles trimming using a separate button placed outside instead of the read more link within the textview itself. Much like one in the project's example. It works fine when there is text longer than the height of the textview.

There is however a side effect. If the text is small, there is no need to toggle the trim button. I need to hide it if the content does not exceed the bounds of the textview.

Is there a way to find this out?

I tried getting the `contentSize` of the textview but it seems to be inaccurate. The content height and the textview frame height returns as equal.

[Demo project](https://www.dropbox.com/s/bke1k93n6mp9vlo/TextTrim.zip?dl=0)

**Comment by ilyapuchka** [comment]
You can try to use `boundingRectForCharacterRange(range:inTextContainer:) -> CGRect` to get the size of the full text range and then compare it with the size of text view.

**Comment by Isuru-Nanayakkara** [comment]
I'm not getting a value even less than what I got using `contentSize`. Below is my code.

```swift
let rect = textView.layoutManager.boundingRectForCharacterRange(range: NSRange(location: 0, length: textView.text.count), inTextContainer: textView.textContainer)
print("TEXT HEIGHT: \(rect.height)")
```

Am I using it correctly?

**Comment by ilyapuchka** [comment]
it might not respect text margins

**Comment by Isuru-Nanayakkara** [comment]
There are no margins though. The textview's height is 128. I have two long paragraphs in it. But the `boundingRectForCharacterRange` method returns 100 as the value.

**Comment by ilyapuchka** [comment]
Try to ask on stackoverflow
