### ISSUE TITLE
how to set color for read more string?

### ISSUE THREAD

**Issue by gemgemo** [ilyapuchka/ReadMoreTextView#9]

**Comment by awind** [comment]
You can set `attributedTrimText` instead of use `trimText`.

**Comment by gemgemo** [comment]
I tried too much and did not work

**Comment by zzj19931010** [comment]
@gemgemo I tried and you have to set trimText to nil and it will work

**Comment by ilyapuchka** [comment]
There is an counterpart property to set attributed text - `attributedRedMoreText`
